const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING"

const FRIEND_JOINED = "FRIEND_JOINED"
const FRIEND_LEFT = "FRIEND_LEFT"

export { ALERT, REFETCH_CHATS, NEW_ATTACHMENT, NEW_MESSAGE_ALERT, NEW_REQUEST, NEW_MESSAGE, START_TYPING, STOP_TYPING, FRIEND_JOINED, FRIEND_LEFT}